name: Project Tests

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Install ffmpeg
        run: choco install ffmpeg --no-progress
        shell: powershell
      - name: Run tests
        if: success() || failure()
        run: |
          pytest
